// AUTO-GENERATED by scripts/gen-types.mts from github.com/lightninglabs/darepo-client/sdk/walletdk
// (darepo-client). Do not edit by hand; run `pnpm gen:types` to refresh.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: client.go

/**
 * Client is the wallet-facing SDK handle. It is safe for concurrent use.
 */
export interface Client {
}

//////////
// source: embedded.go

/**
 * Option mutates the embedded daemon configuration during Start. Functional
 * options express knobs that cannot be modeled by Config's plain-bool
 * enable-only fields, where "leave at zero" cannot be distinguished from
 * "explicit false".
 */
export type Option = any;

//////////
// source: embedded_config.go

/**
 * Config controls the embedded daemon and wallet facade.
 */
export interface Config {
  /**
   * DaemonConfig supplies the full daemon config. When nil, walletdk
   * starts from darepod.DefaultConfig and applies the convenience fields
   * below.
   */
  daemonConfig?: any /* darepod.Config */;
  /**
   * DataDir is the root directory for daemon and wallet state.
   */
  dataDir: string;
  /**
   * Network selects the bitcoin network.
   */
  network: string;
  /**
   * DebugLevel controls daemon logging verbosity.
   */
  debugLevel: string;
  /**
   * LogWriter receives daemon logs. Nil uses darepod's default stdout.
   */
  logWriter: any /* io.Writer */;
  /**
   * AllowMainnet must be true when Network is mainnet. This is an
   * enable-only convenience override; set DaemonConfig directly when
   * a caller-owned config needs an explicit false value.
   */
  allowMainnet: boolean;
  /**
   * ServerAddress is the Ark operator mailbox edge server address.
   */
  serverAddress: string;
  /**
   * ServerTransport selects how the embedded daemon talks to the Ark
   * operator and mailbox edge. Empty defaults to gRPC.
   */
  serverTransport: Transport;
  /**
   * ServerTLSCertPath pins the Ark operator TLS certificate.
   */
  serverTLSCertPath: string;
  /**
   * ServerInsecure disables TLS for the Ark operator connection. This
   * is an enable-only convenience override; set DaemonConfig directly
   * when a caller-owned config needs an explicit false value.
   */
  serverInsecure: boolean;
  /**
   * WalletType selects the backing wallet implementation.
   */
  walletType: string;
  /**
   * WalletEsploraURL is used by the lwwallet backend.
   */
  walletEsploraURL: string;
  /**
   * WalletPasswordFile enables daemon auto-unlock for lwwallet.
   */
  walletPasswordFile: string;
  /**
   * WalletPollInterval overrides the lwwallet chain poll interval.
   */
  walletPollInterval: any /* time.Duration */;
  /**
   * WalletRecoveryWindow overrides the wallet address look-ahead window.
   */
  walletRecoveryWindow: number /* uint32 */;
  /**
   * WalletFeeURL is the fee estimator endpoint used by btcwallet.
   */
  walletFeeURL: string;
  /**
   * WalletBtcwalletBlockHeadersSource is a local file path or HTTP(S)
   * URL that btcwallet/neutrino imports block headers from on startup.
   */
  walletBtcwalletBlockHeadersSource: string;
  /**
   * WalletBtcwalletFilterHeadersSource is a local file path or HTTP(S)
   * URL that btcwallet/neutrino imports compact filter headers from on
   * startup.
   */
  walletBtcwalletFilterHeadersSource: string;
  /**
   * SwapServerAddress is the swapdk-server address for the selected
   * transport.
   */
  swapServerAddress: string;
  /**
   * SwapServerTransport selects how the embedded daemon talks to
   * swapdk-server. Empty defaults to gRPC.
   */
  swapServerTransport: Transport;
  /**
   * SwapServerTLSCertPath pins the swapdk-server TLS certificate.
   */
  swapServerTLSCertPath: string;
  /**
   * SwapServerInsecure disables TLS for the swap server connection.
   * This is an enable-only convenience override; set DaemonConfig
   * directly when a caller-owned config needs an explicit false value.
   */
  swapServerInsecure: boolean;
  /**
   * SwapDatabaseFileName is the daemon-owned swap SQLite database path.
   */
  swapDatabaseFileName: string;
  /**
   * MaxOperatorFeeSat caps the per-round operator fee the daemon accepts.
   */
  maxOperatorFeeSat: number /* int64 */;
  /**
   * EagerRoundJoin makes the embedded daemon's wallet drive
   * round-joining without waiting for a follow-up Board /
   * LeaveVTXOs RPC. With the flag on, freshly confirmed boarding
   * deposits join the next round automatically, and the wallet's
   * Exit / cooperative-leave path fires registration immediately
   * rather than batching. The walletdkrpc-tagged embedded build
   * that walletdk targets already defaults this to true via
   * darepod.DefaultConfig, so leaving this field at the zero
   * value is the right choice for nearly every host. Set true
   * only to force the override when supplying a caller-owned
   * DaemonConfig that currently carries false. To force eager
   * round-join OFF, pass WithEagerRoundJoinDisabled() to Start
   * rather than mutating this field.
   */
  eagerRoundJoin: boolean;
  /**
   * BufferSize overrides the bufconn listener buffer size.
   */
  bufferSize: number /* int */;
}

//////////
// source: passkey.go


//////////
// source: types.go

/**
 * ConnectConfig controls a walletdk client connected to an external daemon.
 */
export interface ConnectConfig {
  /**
   * Address is the target of a daemon exposing walletdkrpc. For gRPC
   * transport this is the gRPC address; for REST transport this is the
   * HTTP gateway base address.
   */
  address: string;
  /**
   * Transport selects how Connect talks to the daemon. Empty defaults to
   * TransportGRPC.
   */
  transport: Transport;
  /**
   * DialOptions are appended to the default dial options. When empty,
   * walletdk uses insecure transport credentials for local development.
   * Only used with TransportGRPC.
   */
  dialOptions: any /* grpc.DialOption */[];
  /**
   * HTTPClient is the HTTP client used with TransportREST. Nil uses
   * http.DefaultClient.
   */
  hTTPClient?: any /* http.Client */;
}
/**
 * Transport selects the RPC transport used by Connect.
 */
export type Transport = "grpc" | "rest";
/**
 * TransportGRPC connects to the daemon with native gRPC.
 */
export const TransportGRPC: Transport = "grpc";
/**
 * TransportREST connects to the daemon through grpc-gateway HTTP/JSON.
 */
export const TransportREST: Transport = "rest";
/**
 * WalletState mirrors the daemon's wallet lifecycle enum so SDK
 * consumers can render wallet setup progress without collapsing
 * LOCKED and SYNCING into one "not ready" state. WalletStateSyncing
 * and WalletStateReady mean seed material is loaded; only
 * WalletStateReady means the wallet is fully usable.
 */
export type WalletState = 0 | 1 | 2 | 3 | 4;
/**
 * WalletStateUnspecified is the proto3 zero value. The daemon
 * never emits this; reserved so a missing field deserializes to
 * a safe non-ready state.
 */
export const WalletStateUnspecified: WalletState = 0;
/**
 * WalletStateNone indicates no wallet has been created yet.
 */
export const WalletStateNone: WalletState = 1;
/**
 * WalletStateLocked indicates an encrypted seed exists but the
 * decryption key has not been provided; signing is unavailable.
 */
export const WalletStateLocked: WalletState = 2;
/**
 * WalletStateReady indicates the wallet is initialized, unlocked,
 * and signing is available.
 */
export const WalletStateReady: WalletState = 3;
/**
 * WalletStateSyncing indicates the wallet is unlocked and the
 * backing chain source is catching up before wallet RPCs are safe.
 */
export const WalletStateSyncing: WalletState = 4;
/**
 * Info summarizes daemon readiness for wallet applications.
 */
export interface Info {
  version: string;
  commit: string;
  network: string;
  blockHeight: number /* uint32 */;
  serverConnected: boolean;
  walletType: string;
  walletState: WalletState;
  identityPubKey: string;
}
/**
 * CreateWalletRequest creates or imports a daemon wallet.
 */
export interface CreateWalletRequest {
  mnemonic: string[];
  seedPassphrase: string /* []byte */;
  walletPassword: string /* []byte */;
  recoverState: boolean;
  recoveryWindow: number /* uint32 */;
}
/**
 * CreateWalletResult returns the seed words, daemon identity, and optional
 * recovery counters.
 */
export interface CreateWalletResult {
  mnemonic: string[];
  encipheredSeed: string /* []byte */;
  identityPubKey: string;
  recoveryRan: boolean;
  recoveredBoardingAddresses: number /* uint32 */;
  recoveredBoardingUTXOs: number /* uint32 */;
  recoveredVTXOs: number /* uint32 */;
  recoveredOORReceiveScripts: number /* uint32 */;
  recoveredOORRecipientEvents: number /* uint32 */;
}
/**
 * UnlockWalletRequest unlocks an existing embedded daemon wallet.
 */
export interface UnlockWalletRequest {
  walletPassword: string /* []byte */;
}
/**
 * UnlockWalletResult returns the daemon identity after unlock.
 */
export interface UnlockWalletResult {
  identityPubKey: string;
}
/**
 * OpenWalletResult reports the outcome of OpenWalletFromPasskey. Imported is
 * true when a new local wallet was created from the derived seed (fresh
 * device); false when an existing local wallet was unlocked. Mnemonic is set
 * only on import, for backup display.
 */
export interface OpenWalletResult {
  imported: boolean;
  mnemonic: string[];
  identityPubKey: string;
}
/**
 * Balance is the wallet-level balance view.
 */
export interface Balance {
  confirmedSat: number /* int64 */;
  pendingInSat: number /* int64 */;
  pendingOutSat: number /* int64 */;
  creditAvailableSat: number /* uint64 */;
  creditReservedSat: number /* uint64 */;
}
/**
 * DepositRequest creates a tracked boarding address.
 */
export interface DepositRequest {
  amountSatHint: number /* uint64 */;
}
/**
 * DepositResult returns a boarding address and its initial activity entry.
 */
export interface DepositResult {
  address: string;
  entry: Entry;
}
/**
 * ReceiveRequest creates a Lightning invoice payable into the wallet.
 */
export interface ReceiveRequest {
  amountSat: number /* uint64 */;
  memo: string;
}
/**
 * ReceiveResult contains the invoice and initial wallet entry.
 */
export interface ReceiveResult {
  invoice: string;
  entry: Entry;
}
/**
 * PrepareSendRequest validates and previews an outbound payment without
 * moving funds.
 */
export interface PrepareSendRequest {
  invoice: string;
  onchainAddress: string;
  amountSat: number /* uint64 */;
  note: string;
  maxFeeSat: number /* uint64 */;
  /**
   * SweepAll drains every live VTXO to OnchainAddress. PrepareSend
   * snapshots the live VTXO set and SendPrepared later spends that
   * exact set. Ignored on the invoice path.
   */
  sweepAll: boolean;
}
/**
 * SendRail identifies the expected settlement rail for a prepared send.
 */
export type SendRail = "unspecified" | "offchain_unknown" | "in_ark" | "lightning" | "onchain" | "credit" | "mixed";
export const SendRailUnspecified: SendRail = "unspecified";
export const SendRailOffchainUnknown: SendRail = "offchain_unknown";
export const SendRailInArk: SendRail = "in_ark";
export const SendRailLightning: SendRail = "lightning";
export const SendRailOnchain: SendRail = "onchain";
export const SendRailCredit: SendRail = "credit";
export const SendRailMixed: SendRail = "mixed";
/**
 * SendQuoteStatus describes how complete the prepare-time quote is.
 */
export type SendQuoteStatus = "unspecified" | "complete" | "local_only";
export const SendQuoteStatusUnspecified: SendQuoteStatus = "unspecified";
export const SendQuoteStatusComplete: SendQuoteStatus = "complete";
export const SendQuoteStatusLocalOnly: SendQuoteStatus = "local_only";
/**
 * PrepareSendResult contains the preview and intent id for a send.
 */
export interface PrepareSendResult {
  sendIntentId: string;
  amountSat: number /* int64 */;
  expectedFeeSat: number /* int64 */;
  feeKnown: boolean;
  expectedTotalOutflowSat: number /* int64 */;
  totalOutflowKnown: boolean;
  rail: SendRail;
  quoteStatus: SendQuoteStatus;
  destinationSummary: string;
  invoiceDescription: string;
  paymentHash: string;
  expiresAtUnix: number /* int64 */;
  selectedOutpoints: string[];
  warning: string;
  creditPreview?: CreditPreview;
}
/**
 * CreditPreview describes how a prepared invoice send will use sat-native
 * server credits.
 */
export interface CreditPreview {
  mustUseCredit: boolean;
  creditAppliedSat: number /* uint64 */;
  creditShortfallSat: number /* uint64 */;
  creditTopupSat: number /* uint64 */;
  arkFundingSat: number /* uint64 */;
}
/**
 * SendPreparedRequest dispatches a prepared outbound payment.
 */
export interface SendPreparedRequest {
  /**
   * SendIntentID is consumed before dispatch. If dispatch returns an
   * error, callers should prepare a fresh send before retrying.
   */
  sendIntentId: string;
}
/**
 * SendResult contains the initial wallet entry for an outbound payment.
 */
export interface SendResult {
  entry: Entry;
  /**
   * ActualAmountSat is the real amount that will leave the wallet for
   * this operation. For invoice sends it matches the invoice principal.
   * For a bounded onchain send it matches the requested amount (the
   * seal-time fee handshake returns change). For a sweep-all onchain
   * send it reflects the swept VTXO total, so host UIs SHOULD echo it
   * back to the user before treating the send as confirmed.
   */
  actualAmountSat: number /* int64 */;
}
/**
 * ListView selects which slice of wallet state List returns. The empty
 * value is treated as ListViewActivity for backwards-feel.
 */
export type ListView = "activity" | "vtxos" | "onchain";
/**
 * ListViewActivity returns the merged WalletEntry stream
 * (send / recv / deposit / exit). Default.
 */
export const ListViewActivity: ListView = "activity";
/**
 * ListViewVTXOs returns the live VTXO inventory.
 */
export const ListViewVTXOs: ListView = "vtxos";
/**
 * ListViewOnchain returns the on-chain transaction history
 * (boarding, sweeps, leave outputs).
 */
export const ListViewOnchain: ListView = "onchain";
/**
 * ListRequest controls wallet activity listing. View selects the slice
 * of wallet state to return; PendingOnly and Kinds apply only when
 * View is ListViewActivity (or empty).
 */
export interface ListRequest {
  /**
   * View selects the response shape. Empty is treated as
   * ListViewActivity.
   */
  view: ListView;
  /**
   * PendingOnly applies to ListViewActivity only.
   */
  pendingOnly: boolean;
  /**
   * Kinds applies to ListViewActivity only.
   */
  kinds: EntryKind[];
  /**
   * Limit caps the page size; zero uses the daemon default.
   */
  limit: number /* uint32 */;
  /**
   * Offset is the pagination offset within the chosen view.
   */
  offset: number /* uint32 */;
}
/**
 * ListResult is a tagged union: exactly one of Activity, VTXOs, or
 * Onchain is populated according to the view requested. Callers should
 * switch on View to pick the right field.
 */
export interface ListResult {
  /**
   * View is the populated variant. Mirrors ListRequest.View; an
   * empty request view is reported as ListViewActivity.
   */
  view: ListView;
  /**
   * Activity is populated when View == ListViewActivity.
   */
  activity?: ActivityList;
  /**
   * VTXOs is populated when View == ListViewVTXOs.
   */
  vtxos?: VTXOInventory;
  /**
   * Onchain is populated when View == ListViewOnchain.
   */
  onchain?: OnchainHistory;
}
/**
 * ActivityList is the merged WalletEntry stream returned by the
 * activity view.
 */
export interface ActivityList {
  entries: Entry[];
  total: number /* uint32 */;
}
/**
 * VTXOInventory is the live VTXO inventory returned by the vtxos view.
 */
export interface VTXOInventory {
  vtxos: WalletVTXO[];
  total: number /* uint32 */;
}
/**
 * WalletVTXO is the wallet-facing view of one VTXO. Internal lifecycle
 * detail (forfeiting flow, chain depth) is hidden; power-users reach
 * the full shape via `ark vtxos list`.
 */
export interface WalletVTXO {
  outpoint: string;
  amountSat: number /* int64 */;
  status: string;
  batchExpiry: number /* int32 */;
  relativeExpiry: number /* uint32 */;
  commitmentTxid: string;
}
/**
 * OnchainHistory is the on-chain transaction history returned by the
 * onchain view.
 */
export interface OnchainHistory {
  txs: OnchainTx[];
  total: number /* uint32 */;
  hasMore: boolean;
}
/**
 * OnchainTx is the wallet-facing view of one on-chain transaction.
 */
export interface OnchainTx {
  txid: string;
  kind: string;
  amountSat: number /* int64 */;
  feeSat: number /* int64 */;
  status: string;
  confirmationHeight: number /* int32 */;
  createdAt: string;
  description: string;
}
/**
 * ExitRequest triggers an exit for a VTXO outpoint. When Destination is
 * set, the SDK first attempts a cooperative leave (LeaveVTXOs RPC) with
 * the leave output bound for the supplied on-chain address; if that path
 * succeeds, the SDK returns a cooperative result. Unilateral unroll is
 * reachable only when ForceUnrollAck carries the daemon's exact
 * acknowledgement string.
 */
export interface ExitRequest {
  /**
   * Outpoint identifies the VTXO to exit in "txid:index" format.
   */
  outpoint: string;
  /**
   * Destination is the on-chain address that receives the leave
   * output when the cooperative path succeeds. The address must be
   * valid for the daemon's configured network. Empty asks the daemon
   * to generate a fresh backing-wallet destination internally.
   */
  destination: string;
  /**
   * ForceUnrollAck must be exactly "I_KNOW_WHAT_I_AM_DOING" to bypass
   * cooperative leave and start unilateral unroll. Cannot be combined
   * with Destination; the server rejects the pair with InvalidArgument.
   */
  forceUnrollAck: string;
}
/**
 * ExitPath identifies which branch of the Exit decision tree the
 * daemon ended up taking. Callers should switch on Path rather than
 * chaining nil-checks across the result's variant fields.
 */
export type ExitPath = "cooperative" | "unilateral" | "unilateral_fallback";
/**
 * ExitPathCooperative means the cooperative leave was admitted by
 * the operator; QueuedOutpoints carries the round's selection
 * echo. Cooperative round completion is asynchronous; subscribe
 * via walletdkrpc.SubscribeWallet to confirm terminal state.
 */
export const ExitPathCooperative: ExitPath = "cooperative";
/**
 * ExitPathUnilateral means the caller supplied the exact force
 * acknowledgement and the daemon started unilateral unroll. Created
 * and ActorID describe the unilateral unroll job.
 */
export const ExitPathUnilateral: ExitPath = "unilateral";
/**
 * ExitPathUnilateralFallback is retained for source compatibility
 * with the prior SDK result shape. New forced unrolls return
 * ExitPathUnilateral; current wallet RPC behavior never returns this
 * path because cooperative failures are surfaced directly.
 */
export const ExitPathUnilateralFallback: ExitPath = "unilateral_fallback";
/**
 * ExitResult is a tagged union over the three exit paths. Callers
 * should read Path first and only inspect the variant fields
 * associated with that path; the remaining fields are zero-valued.
 */
export interface ExitResult {
  /**
   * Path discriminates between the three legal outcomes; callers
   * MUST switch on Path before reading the variant fields below.
   */
  path: ExitPath;
  /**
   * Cooperative is true iff Path == ExitPathCooperative. Retained
   * for backwards compatibility with the v1 result shape; new
   * callers should prefer Path.
   */
  cooperative: boolean;
  /**
   * QueuedOutpoints lists the outpoints the cooperative leave
   * admitted into a round. Populated only when
   * Path == ExitPathCooperative.
   */
  queuedOutpoints: string[];
  /**
   * Created reports whether the unilateral-unroll path spawned a
   * fresh job. Populated when Path is ExitPathUnilateral or
   * ExitPathUnilateralFallback.
   */
  created: boolean;
  /**
   * ActorID identifies the durable unroll job that owns the
   * unilateral path. Populated when Path is ExitPathUnilateral or
   * ExitPathUnilateralFallback.
   */
  actorID: string;
  /**
   * CooperativeError is retained for source compatibility with the
   * prior SDK fallback result shape. Current wallet RPC behavior never
   * populates it because cooperative failures are returned directly
   * instead of falling back to unilateral unroll.
   */
  cooperativeError: string;
}
/**
 * ExitStatusRequest queries the current phase of an exit job.
 */
export interface ExitStatusRequest {
  outpoint: string;
}
/**
 * ExitJobStatus collapses the underlying unroll job phases to a short
 * wallet-facing string set.
 */
export type ExitJobStatus = "unspecified" | "pending" | "materializing" | "csv_pending" | "sweeping" | "completed" | "failed";
export const ExitJobStatusUnspecified: ExitJobStatus = "unspecified";
export const ExitJobStatusPending: ExitJobStatus = "pending";
export const ExitJobStatusMaterializing: ExitJobStatus = "materializing";
export const ExitJobStatusCSVPending: ExitJobStatus = "csv_pending";
export const ExitJobStatusSweeping: ExitJobStatus = "sweeping";
export const ExitJobStatusCompleted: ExitJobStatus = "completed";
export const ExitJobStatusFailed: ExitJobStatus = "failed";
/**
 * ExitStatusResult reports the status of one exit job. Found is false
 * when no job exists for the requested outpoint (not an error).
 */
export interface ExitStatusResult {
  found: boolean;
  status: ExitJobStatus;
  sweepTxid: string;
  lastError: string;
}
/**
 * GetExitPlanRequest previews unilateral-exit readiness for a slice of VTXOs.
 */
export interface GetExitPlanRequest {
  outpoints: string[];
  confTarget: number /* uint32 */;
}
/**
 * ExitPlanEntry describes how to fund the backing wallet before Exit for a
 * single previewed VTXO outpoint.
 */
export interface ExitPlanEntry {
  outpoint: string;
  fundingAddress: string;
  requiredConfirmations: number /* uint32 */;
  requiredFeeUTXOCount: number /* uint32 */;
  usableFeeUTXOCount: number /* uint32 */;
  recommendedUTXOAmountSat: number /* int64 */;
  recommendedTotalFundingSat: number /* int64 */;
  fundingShortfallSat: number /* int64 */;
  canStart: boolean;
  exitJobFound: boolean;
  exitStatus: ExitJobStatus;
  sweepTxid: string;
  lastError: string;
  /**
   * Err is a per-outpoint failure (empty on success).
   */
  err: string;
}
/**
 * GetExitPlanResult describes the combined backing-wallet funding plan for
 * every previewed outpoint plus aggregate totals.
 */
export interface GetExitPlanResult {
  plans: ExitPlanEntry[];
  feeRateSatPerVByte: number /* int64 */;
  canStart: boolean;
  totalFundingShortfallSat: number /* int64 */;
  totalRecommendedFundingSat: number /* int64 */;
}
/**
 * SweepWalletRequest previews or broadcasts a backing-wallet sweep.
 */
export interface SweepWalletRequest {
  destinationAddress: string;
  broadcast: boolean;
  feeRateSatPerVByte: number /* int64 */;
  confTarget: number /* uint32 */;
}
/**
 * WalletSweepInput describes one backing-wallet UTXO selected by SweepWallet.
 */
export interface WalletSweepInput {
  outpoint: string;
  amountSat: number /* int64 */;
}
/**
 * SweepWalletResult contains the selected inputs and optional broadcast txid.
 */
export interface SweepWalletResult {
  inputs: WalletSweepInput[];
  totalInputSat: number /* int64 */;
  estimatedFeeSat: number /* int64 */;
  netAmountSat: number /* int64 */;
  feeRateSatPerVByte: number /* int64 */;
  canBroadcast: boolean;
  txid: string;
  failureReason: string;
}
/**
 * Status summarizes wallet readiness and pending activity.
 */
export interface Status {
  ready: boolean;
  unlocked: boolean;
  network: string;
  balance: Balance;
  pendingCount: number /* uint32 */;
}
/**
 * SubscribeRequest controls wallet activity subscriptions.
 */
export interface SubscribeRequest {
  includeExisting: boolean;
  kinds: EntryKind[];
}
/**
 * EntryKind is the user-visible wallet activity category.
 */
export type EntryKind = "send" | "receive" | "deposit" | "exit";
/**
 * EntryKindSend is an outbound wallet payment.
 */
export const EntryKindSend: EntryKind = "send";
/**
 * EntryKindReceive is an inbound Lightning-to-wallet receive.
 */
export const EntryKindReceive: EntryKind = "receive";
/**
 * EntryKindDeposit is a boarding on-chain deposit.
 */
export const EntryKindDeposit: EntryKind = "deposit";
/**
 * EntryKindExit is a cooperative wallet-to-on-chain exit.
 */
export const EntryKindExit: EntryKind = "exit";
/**
 * EntryStatus is the collapsed wallet activity state.
 */
export type EntryStatus = "pending" | "complete" | "failed";
/**
 * EntryStatusPending means the activity is still in flight.
 */
export const EntryStatusPending: EntryStatus = "pending";
/**
 * EntryStatusComplete means the activity finished successfully.
 */
export const EntryStatusComplete: EntryStatus = "complete";
/**
 * EntryStatusFailed means the activity reached a terminal failure.
 */
export const EntryStatusFailed: EntryStatus = "failed";
/**
 * Entry is the wallet-facing activity row used by UI and bridge layers.
 */
export interface Entry {
  id: string;
  kind: EntryKind;
  status: EntryStatus;
  amountSat: number /* int64 */;
  feeSat: number /* int64 */;
  counterparty: string;
  createdAt: string;
  updatedAt: string;
  note: string;
  failureReason: string;
  /**
   * Progress carries the lifecycle metadata the daemon already
   * normalized for this entry (phase, payment hash, txid, confirmation
   * height, vHTLC outpoint). It is nil when the backing subsystem
   * supplied no progress hint.
   */
  progress?: EntryProgress;
  /**
   * Request echoes the user-recognizable request that created the entry
   * (a Lightning invoice, an on-chain address, or an Ark address). It is
   * nil when the backing subsystem did not persist one.
   */
  request?: EntryRequest;
  /**
   * FailureCode is a stable, machine-readable classification of why the
   * entry failed. It is empty unless Status is failed, mirroring
   * FailureReason, which remains the human-readable supplement.
   */
  failureCode: EntryFailureCode;
}
/**
 * EntryPhase is a coarse, wrapper-owned lifecycle phase for an Entry. It does
 * not replace Status: Status answers pending/complete/failed, while Phase
 * explains the current backing-system step. Like the other Entry enums it is
 * a lowercase string decoupled from the proto enum so renumbering cannot break
 * callers; switch on it rather than comparing proto values.
 */
export type EntryPhase = "unspecified" | "request_created" | "waiting_for_payment" | "payment_detected" | "settling" | "confirmed" | "refunding" | "refunded" | "failed" | "waiting_for_confirmation";
/**
 * EntryPhaseUnspecified means the backing subsystem provided no
 * lifecycle hint.
 */
export const EntryPhaseUnspecified: EntryPhase = "unspecified";
/**
 * EntryPhaseRequestCreated means the request was created but no payment
 * has been observed yet.
 */
export const EntryPhaseRequestCreated: EntryPhase = "request_created";
/**
 * EntryPhaseWaitingForPayment means the wallet is waiting for an
 * inbound payment or swap funding.
 */
export const EntryPhaseWaitingForPayment: EntryPhase = "waiting_for_payment";
/**
 * EntryPhasePaymentDetected means a payment was detected but is not yet
 * settled.
 */
export const EntryPhasePaymentDetected: EntryPhase = "payment_detected";
/**
 * EntryPhaseSettling means the operation is settling through Ark,
 * Lightning, or on-chain machinery.
 */
export const EntryPhaseSettling: EntryPhase = "settling";
/**
 * EntryPhaseConfirmed means the backing operation is confirmed or
 * otherwise durably complete.
 */
export const EntryPhaseConfirmed: EntryPhase = "confirmed";
/**
 * EntryPhaseRefunding means the operation is currently refunding.
 */
export const EntryPhaseRefunding: EntryPhase = "refunding";
/**
 * EntryPhaseRefunded means the refund path completed.
 */
export const EntryPhaseRefunded: EntryPhase = "refunded";
/**
 * EntryPhaseFailed means the backing operation reached a terminal
 * failed state.
 */
export const EntryPhaseFailed: EntryPhase = "failed";
/**
 * EntryPhaseWaitingForConfirmation means an on-chain payment was
 * detected and is waiting for block confirmation.
 */
export const EntryPhaseWaitingForConfirmation: EntryPhase = "waiting_for_confirmation";
/**
 * EntryProgress is the wrapper-owned view of the lifecycle metadata the daemon
 * computes for an Entry. Fields are populated on a best-effort basis by the
 * backing subsystem; an empty field means "not applicable / not yet known".
 */
export interface EntryProgress {
  /**
   * Phase is the coarse lifecycle phase for the entry.
   */
  phase: EntryPhase;
  /**
   * PhaseLabel is the short lowercase label the daemon emitted; clients
   * may render it directly instead of switching on Phase.
   */
  phaseLabel: string;
  /**
   * PaymentHash is populated for Lightning-backed send/recv entries.
   */
  paymentHash: string;
  /**
   * Txid is populated when the backing ledger row has an on-chain txid.
   */
  txid: string;
  /**
   * ConfirmationHeight is populated once the source records it.
   */
  confirmationHeight: number /* int32 */;
  /**
   * VTXOOutpoint is populated when a swap observes the Ark vHTLC output.
   */
  vTXOOutpoint: string;
  /**
   * Preimage is the hex-encoded Lightning payment preimage once the swap
   * revealed it. For a completed Lightning-backed send this is the proof
   * of payment for the paid invoice (sha256(preimage) == PaymentHash); it
   * is empty until durably known and for non-Lightning entries.
   */
  preimage: string;
}
/**
 * EntryRequestType discriminates which request shape an EntryRequest carries.
 * Callers should switch on Type before reading the variant fields.
 */
export type EntryRequestType = "lightning" | "onchain" | "ark";
/**
 * EntryRequestTypeLightning marks a Lightning send/recv request; the
 * LightningInvoice and PaymentHash fields are populated.
 */
export const EntryRequestTypeLightning: EntryRequestType = "lightning";
/**
 * EntryRequestTypeOnchain marks a deposit/exit request; the
 * OnchainAddress field is populated.
 */
export const EntryRequestTypeOnchain: EntryRequestType = "onchain";
/**
 * EntryRequestTypeArk marks a direct Ark send/recv request; the
 * ArkAddress field is populated.
 */
export const EntryRequestTypeArk: EntryRequestType = "ark";
/**
 * EntryRequest is the wrapper-owned, flattened view of the proto request
 * oneof. Exactly one variant's fields are populated, named by Type; read Type
 * first and treat the other fields as zero.
 */
export interface EntryRequest {
  /**
   * Type names the populated variant.
   */
  type: EntryRequestType;
  /**
   * LightningInvoice is the BOLT-11 payment request. Populated when Type
   * is EntryRequestTypeLightning.
   */
  lightningInvoice: string;
  /**
   * PaymentHash identifies the Lightning invoice and stays stable after
   * the invoice is no longer convenient to display. Populated when Type
   * is EntryRequestTypeLightning.
   */
  paymentHash: string;
  /**
   * OnchainAddress is the bech32 on-chain address originally issued or
   * targeted. Populated when Type is EntryRequestTypeOnchain.
   */
  onchainAddress: string;
  /**
   * ArkAddress is the Ark address originally issued or targeted.
   * Populated when Type is EntryRequestTypeArk.
   */
  arkAddress: string;
}
/**
 * EntryFailureCode is a wrapper-owned, stable classification of why a failed
 * Entry failed. Like the other Entry enums it is a lowercase string decoupled
 * from the proto enum; switch on it rather than comparing proto values.
 */
export type EntryFailureCode = "timed_out" | "expired" | "refunded" | "needs_intervention" | "failed";
/**
 * EntryFailureCodeTimedOut means the operation exceeded the wallet
 * deadline before reaching a terminal state.
 */
export const EntryFailureCodeTimedOut: EntryFailureCode = "timed_out";
/**
 * EntryFailureCodeExpired means the swap expired before it was funded.
 */
export const EntryFailureCodeExpired: EntryFailureCode = "expired";
/**
 * EntryFailureCodeRefunded means an outbound payment was refunded back
 * to the wallet.
 */
export const EntryFailureCodeRefunded: EntryFailureCode = "refunded";
/**
 * EntryFailureCodeNeedsIntervention means the swap reached an anomalous
 * state requiring manual recovery.
 */
export const EntryFailureCodeNeedsIntervention: EntryFailureCode = "needs_intervention";
/**
 * EntryFailureCodeFailed is a generic terminal failure with no more
 * specific classification.
 */
export const EntryFailureCodeFailed: EntryFailureCode = "failed";
